src/inout.cpp File Reference
Manage input/output.
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <fstream>
Classes
struct INSTANCE
Structure used to define the instance data.
Functions
int readProblemData (char * _FILENAME, int fType, INSTANCE & inp)
Read benchmark instances.
void printOptions (char * _FILENAME, INSTANCE inp, int timeLimit)
Print instance info and algorithmic parameters.
void read_parameters_ellipsoidal (double &epsilon, double &Omega)
Read parameters to define the ellipsoidal uncertainty set.
void read_parameters_box (double &epsilon)
Read parameters to define the Box support.
void read_parameters_budget (double &epsilon, double &delta, double &gamma, int &L)
Read parameters to define the budget support.
Variables
string instanceType
string versionType
string supportType
Detailed Description
Manage input/output.
We manage here the following operations:
Read nominal instance from disk (both OR Library and Avella). See the introduction part of rcflp.cpp to see how the costs $c_{ij}$ are managed in the two instance types.
Read parameters for the different support sets. Currently, we read parameters for the following sets:
Ellipsoidal support set. See read_parameters_ellipsoidal()
Box support set. See read_parameters_box()
Budget support set. See read_parameters_budget()
Function Documentation
printOptions()
void printOptions (char * _FILENAME, INSTANCE inp, int timeLimit)
Print instance info and algorithmic parameters.
References instanceType, INSTANCE::nC, INSTANCE::nF, supportType, and versionType.
Referenced by main().
read_parameters_box()
void read_parameters_box (double & epsilon)
Read parameters to define the Box support.
The file 'paramsBox.txt' has the following format:
first row : epsilon, i.e., the parameter used to define the with of the box. Given a nominal demand value $d_j$, we define the interval around $d_j$ as:
 (1-\epsilon)*d_j <= d_j <= (1+\epsilon)d_j, \quad 0 \leq \epsilon \leq 1 
Referenced by define_box_support().
read_parameters_budget()
void read_parameters_budget (double & epsilon, double & delta, double & gamma, int & L)
Read parameters to define the budget support.
File : paramsBudget.txt
first row : epsilon, as above
second row: delta, i.e., how the $b_l$ value (the r.h.s. value of each budget constraint) is defined. We define $b_l$ as a percentage of the total demand of customers included in the budget constraint, i.e.:
 b_l = \delta* (\sum_{j \in B_l} d_j), \quad 0 \leq \delta \leq 1 
third row : gamma, i.e., percentage of columns included in each budget constraint:
|B_l| = \lfloor \gamma n \rfloor, \quad 0 \leq \gamma \leq 1
forth row : $L \geq 1$, i.e., number of budget constraints.
Referenced by define_budget_support().
read_parameters_ellipsoidal()
void read_parameters_ellipsoidal (double & epsilon, double & Omega)
Read parameters to define the ellipsoidal uncertainty set.
We need to define two parameters:
Omega : It determines the size of the ellipsoidal, i.e., the size of the uncertainty set.
epsilon: It defines the variance of each variable $x_{ij}$. We assume that the covariance matrix is diagonal and with constant values $\epsilon$ for each element.
Referenced by define_SOCP_CFLP().
readProblemData()
int readProblemData (char * _FILENAME, int fType, INSTANCE & inp)
Read benchmark instances.
Currently, two types of instances can be imported: type 1: OR Library type 2: Avella (Test Bed 1, Test Bed A. Test Bed B)
References INSTANCE::c, INSTANCE::d, INSTANCE::f, INSTANCE::nC, INSTANCE::nF, INSTANCE::s, INSTANCE::totD, and INSTANCE::totS.
Referenced by main().
Variable Documentation
instanceType
string instanceType
Referenced by printOptions(), and printSolution().
supportType
string supportType
Referenced by printOptions(), and printSolution().
versionType
string versionType
Referenced by printOptions(), and printSolution().