src/rcflp.cpp File Reference
General Implementation of the compact formulations for the (R)-CFLP.
#include <ilcplex/ilocplex.h>
#include <limits>
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <cstring>
#include <string>
#include <cmath>
#include <climits>
#include <cfloat>
#include <cassert>
#include <random>
#include <algorithm>
#include `options.h`
Classes
struct INSTANCE
Structure used to define the instance data.
struct SOLUTION
Optimal solution and obj function value.
Typedefs
typedef std::vector< int > MyVect
typedef IloArray< IloNumVarArray > TwoD
Functions
mt19937_64 gen (seed)
64-bit Mersenne Twister by Matsumoto and Nishimura, 2000
IloModel model (env, `cflp`)
IloCplex cplex (model)
int readProblemData (char * _FILENAME, int fType, INSTANCE & inp)
Read benchmark instances.
void printOptions (char * _FILENAME, INSTANCE inp, int timeLimit)
Print instance info and algorithmic parameters.
void define_MS_CFLP (INSTANCE inp, int fType, IloModel & model, IloCplex & cplex)
Define the Multi-source Capacitated Facility Location Model [Nominal].
void define_SS_CFLP (INSTANCE inp, int fType, IloModel & model, IloCplex & cplex)
Define the Single-source Capacitated Facility Location Model [Nominal].
void define_SOCP_CFLP (INSTANCE inp, int fType, IloModel & model, IloCplex & cplex)
Define the Multi-source Capacitated Facility Location Model [Ellipsoidal].
void define_POLY_CFLP (INSTANCE inp, int fType, IloModel & model, IloCplex & cplex, int support)
Define robust model based on polyhedral uncertainty set.
int solveCplexProblem (IloModel model, IloCplex cplex, INSTANCE inp, int solLimit, int timeLimit, int displayLimit)
Set cplex parameters and solve the optimization problem.
void getCplexSol (INSTANCE inp, IloCplex cplex, SOLUTION & opt)
END main program.
void printSolution (char * _FILENAME, INSTANCE inp, SOLUTION opt, bool toDisk, int fullOutput)
Print solution to screen (and disk, if required)
void read_parameters_box (double &delta)
Read parameters to define the Box support.
void read_parameters_ellipsoidal (double &epsilon, double &Omega)
Read parameters to define the ellipsoidal uncertainty set.
void read_parameters_budget (double &epsilon, double &delta, double &gamma, int &L)
Read parameters to define the budget support.
void define_box_support (INSTANCE & inp)
Define $W$ and $\mathbf{h}$, given the value of epsilon.
void define_budget_support (INSTANCE & inp, bool fromDisk)
Read parameters to define the Budget support.
void save_instance_2_disk (double epsilon, double delta, double gamma, int L, int nBl, int **Bl, double *budget)
Save Budget Uncertainty Set Info on disk.
void read_instance_from_disk (double &epsilon, double &delta, double &gamma, int &L, int &nBl, int **Bl, double *budget)
Read a robust instance based on budget uncertainty set.
int main (int argc, char *argv[])
main program
Variables
double INFTY = std::numeric_limits<double>::infinity()
const long _MAXRANDOM = 2147483647
const double ZERO = 0.0e0
const double EPSI = 0.00001
const int seed = 27
Initialization of Random Number Generator.
char * _FILENAME
Instance name file.
int fType
instance type (1-4)
int version
1-SS; 2-MS; 3-SOCP
int support
1-Box; 2-Budget
string instanceType
string versionType
string supportType
 INSTANCE inp
Instance data.
 SOLUTION opt
Solution data structure.
IloEnv env
 TwoD x_ilo
IloNumVarArray y_ilo
IloNumVarArray q_ilo
IloNumVar w_ilo
 TwoD psi_ilo
IloNumVarArray u_ilo
IloNumVarArray delta_ilo
int solLimit = 9999
int displayLimit = 4
int timeLimit
wall-clock time limit
Detailed Description
General Implementation of the compact formulations for the (R)-CFLP.
Different Versions of the CFLP
We define here the following variants of the CFLP. For a full description of the different variants, along with other parameters, see options.cpp.
Current versions of the CFLP implemented here are (controlled via the command line flag -v):
Single Source Nominal: see define_SS_CFLP()
Multi Source Nominal: see define_MS_CFLP()
Ellipsoidal Support Set (multi-source only?): see define_SOCP_CFLP()
Polyhedra Support Set (both single and multi-source): see define_POLY_CFLP()
Instance Types
In addition, we need to define the type of instance used. We are currently working with the following instances (controlled via the command line flag -t):
1 : OR Library instances
2 : Avella instances (Type 1, Type A, Type B)
Note: These instances define the costs in different ways and, therefore the way in which the $x_{ij}$ variables are defined changes. More precisely:
For the OR Library instances, the $c_{ij}$ values are the cost of delivering the entire demand to the customer. Thus, we define $x_{ij}$ as fractional and multiply $c_{ij}\times x_{ij}$ to get the real cost.
For the Avella instances, $c_{ij}$ is the cost of transporting one unit. Thus, $x_{ij}$ is no longer the fraction of demand, but the actual number of units transported.
Obviously, this different treatment of the $x_{ij}$ variables has an effect on the definition of the demand and capacity constraints as well. Therefore, to make the treatment of the two types of instances uniform, the cost $c_{ij}$ of the OR Library is divided by the total demand:
 c_{ij} = \frac{c_{ij}}{d_j} 
To summarize, after the transformation, for both instance types (OR Library and Avella), we have:
$x_{ij} \in [0,1]$ : percentage of demand
$c_{ij}$ : cost of delivering one unit of demand
$d_j$ : total demand of customer $j$
This allows to define the demand constraint as:
 \sum_{i=1}^m x_{ij} = 1 
 and the capacity constraint as:
 \sum_{j=1}^m d_j x_{ij} \leq s_iy_i 
 Finally, the transportation cost is computed as:
 \sum_{i=1}^m \sum_{j=1}^n d_jx_{ij}c_{ij} 
MIP Solver
We use cplex to solve the different programs. See the makefile to determine how to link the library to the code.
Typedef Documentation
MyVect
typedef std::vector<int> MyVect
TwoD
typedef IloArray<IloNumVarArray> TwoD
Function Documentation
cplex()
IloCplex cplex (model)
Referenced by main().
define_box_support()
void define_box_support (INSTANCE & inp)
Define $W$ and $\mathbf{h}$, given the value of epsilon.
We need to define $W\mathbf{d} \leq \mathbf{h}$, where:
$W$ is of size [r x n]
$\mathbf{h}$ is of size [r x 1] where:
$r = 2n$ (two elements for each column $j$)
$n =$ number of customers
Since matrix $W$ is sparse, we use a column major format as follows. Consider the toy problem, for which matrix $W$ and vector $\mathbf{h}$ are:
 W = \left[\begin{array}{rrr} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & -1 \\ 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\ \end{array}\right] \quad \textbf{d} = \left[\begin{array}{ccc} d_1 \\ d_2 \\ d_3 \end{array}\right] \quad \textbf{h} =\left[ \begin{array}{r} -d_0(1-\epsilon) \\ -d_1(1-\epsilon) \\ -d_2(1-\epsilon) \\ d_0(1+\epsilon) \\ d_1(1+\epsilon) \\ d_2(1+\epsilon) \end{array}\right] 
Vector h is kept as is it, while matrix W uses a column major format:
W = [-1 1 -1 1 -1 1]
start = [0 2 4 6]
index = [0 3 1 4 2 5]
where elements of column j in W and index are found in positions going from start[j] to start[j+1] (note that vector start contains a final extra element to close the cycle). Thus, e.g., the elements of the second column of W (j = 1) are obtained as:
for (int l = start[j]; l < start[j+1]; l++)
     W[l] is the element in row index[l] of the matrix
References INSTANCE::d, INSTANCE::h, INSTANCE::index, INSTANCE::nC, INSTANCE::nR, read_parameters_box(), INSTANCE::start, and INSTANCE::W.
Referenced by define_POLY_CFLP().
define_budget_support()
void define_budget_support (INSTANCE & inp, bool fromDisk)
Read parameters to define the Budget support.
We allow for two options here:
case 1: Create the budget support from the nominal values of the instance. In this case, we read the parameters from the disk file (see below) and we generate the polyhedron. This is a stochastic process, since the set of columns included in each budget constrain is randomly generated. Therefore, to ensure reproducibility, we save these values in a disk file, within the folder `support.`
case 2: Read the budget support from the disk. This allows to reproduce the results of an instance, by recreating the same budget support set.
The file paramsBudget.txt has the following format:
first row : epsilon, as above
second row: delta, i.e., how the $b_l$ value (the r.h.s. value of each budget constraint) is defined. We define $b_l$ as a percentage of the total demand of customers included in the budget constraint, i.e.:
 b_l = \delta* (\sum_{j \in B_l} d_j), \quad 0 \leq \delta \leq 1 
third row : gamma, i.e., percentage of columns included in each budget constraint:
|B_l| = \lfloor \gamma n \rfloor, \quad 0 \leq \gamma \leq 1
forth row : $L \geq 1$, i.e., number of budget constraints.
The structure of $W$ and $\mathbf{h}$ and the column-major format used is simular to the one employed in define_box_support(). The first $2n$ rows of $W$ are identical to the box support. Next, we define $L$ extra rows, to include the budget constraints. Consider budget constraint $l$, associated to set $B_l$. This row is defined as follows:
 w_{lj} = \left\{ \begin{array}{ll} 1, & j \in B_l \\ 0, & \mbox{otherwise} \end{array} \right. 
 For example, if we want to add the following budget constraint (following the example from the paper):
 d_1 + d_2 + d_3 \leq 4 
 where we have $L=1$, $B_l =\left\{1,2,3\right\}$, we obtain:
 W = \left[\begin{array}{rrr} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & -1 \\ 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\ 1 & 1 & 1 \\ \end{array}\right] \quad \textbf{d} = \left[\begin{array}{ccc} d_1 \\ d_2 \\ d_3 \end{array}\right] \quad \textbf{h} =\left[ \begin{array}{r} -d_0(1-\epsilon) \\ -d_1(1-\epsilon) \\ -d_2(1-\epsilon) \\ d_0(1+\epsilon) \\ d_1(1+\epsilon) \\ d_2(1+\epsilon) \\ 4 \\ \end{array}\right] 
Consequently, in terms of column-major format, we get:
W = [-1 1 1 -1 1 1 -1 1 1]
start = [0 3 6 9]
index = [0 3 6 1 4 6 2 5 6]
References INSTANCE::d, gen(), INSTANCE::h, INSTANCE::index, INSTANCE::nC, INSTANCE::nR, read_instance_from_disk(), read_parameters_budget(), save_instance_2_disk(), INSTANCE::start, and INSTANCE::W.
Referenced by define_POLY_CFLP().
define_MS_CFLP()
void define_MS_CFLP (INSTANCE inp, int fType, IloModel & model, IloCplex & cplex)
Define the Multi-source Capacitated Facility Location Model [Nominal].
References INSTANCE::c, INSTANCE::d, env, INSTANCE::f, INSTANCE::nC, INSTANCE::nF, INSTANCE::s, x_ilo, and y_ilo.
Referenced by main().
define_POLY_CFLP()
void define_POLY_CFLP (INSTANCE inp, int fType, IloModel & model, IloCplex & cplex, int support)
Define robust model based on polyhedral uncertainty set.
We implement here both the SINGLE SOURCE and the MULTI SOURCE versions. Just change the way in which the allocation variables x_ilo are defined, to switch between the SS and the MS versions. The notation here follows the one presented in the paper.
Each support type is build from the nominal instance. That is, we read the instance from disk, we read a few parameters (depending on the support type) and we then build the support set around the nominal values provided by the instance.
The polyhedral uncertainty set is defined in the form:
 W\mathbf{d} \leq \mathbf{h} 
 Therefore, before we can solve the corresponding model, we need to define the structure of $W$ and $\mathbf{h}$:
$W$ is of size $r \times n$, where $r$ is the number of budget constraints we want to define;
$\mathbf{h}$ is of size $r \times 1$.
The support set is defined in a different function, depending on the type of support we want to define (box, budget, etc.) The functions define_type_support() is used to create $W$ and $\mathbf{h}$. Each support type requires a set of parameters. These parameters are read from disk and are stored in a file saved in the folder `parameters`. The file name is of type paramsSupportType.txt. Each file contains comments w.r.t. how to interpret the parameters. However, the interpretation is as follows:
File : paramsBox.txt
first row : epsilon, i.e., the parameter used to define the with of the box. Given a nominal demand value $d_j$, we define the interval around $d_j$ as:
 (1-\epsilon)*d_j <= d_j <= (1+\epsilon)d_j, \quad 0 \leq \epsilon \leq 1 
File : paramsBudget.txt
first row : epsilon, as above
second row: delta, i.e., how the $b_l$ value (the r.h.s. value of each budget constraint) is defined. We define $b_l$ as a percentage of the total demand of customers included in the budget constraint, i.e.:
 b_l = \delta* (\sum_{j \in B_l} d_j), \quad 0 \leq \delta \leq 1 
third row : gamma, i.e., percentage of columns included in each budget constraint:
|B_l| = \lfloor \gamma n \rfloor, \quad 0 \leq \gamma \leq 1
forth row : $L \geq 1$, i.e., number of budget constraints.
To define which columns are included in each budget constraint, we first compute the cardinality of each set $B_l$ (using gamma); next, we randomly select $\gamma \times n$ columns from the set $N = \left\{0, ..., n-1\right\}$.
Note: Sets $B_l$, with $l = 1, ..., L$, are NOT disjoint, i.e., the same customer j can appear in more than one budget constraint.
To test it, use the toy problem, whose instance values are defined in the file 'data/toy.txt'. These values are the one reported in the paper, under the example section. Changing the value of the parametes above, we can transform a robust problem into a nomimal one (e.g., setting $\epsilon = 0$ in box support.)
References INSTANCE::c, define_box_support(), define_budget_support(), delta_ilo, env, INSTANCE::f, INSTANCE::h, INSTANCE::index, INSTANCE::nC, INSTANCE::nF, INSTANCE::nR, psi_ilo, INSTANCE::s, INSTANCE::start, u_ilo, INSTANCE::W, x_ilo, and y_ilo.
Referenced by main().
define_SOCP_CFLP()
void define_SOCP_CFLP (INSTANCE inp, int fType, IloModel & model, IloCplex & cplex)
Define the Multi-source Capacitated Facility Location Model [Ellipsoidal].
References INSTANCE::c, INSTANCE::d, env, INSTANCE::f, INSTANCE::nC, INSTANCE::nF, q_ilo, read_parameters_ellipsoidal(), INSTANCE::s, w_ilo, x_ilo, and y_ilo.
Referenced by main().
define_SS_CFLP()
void define_SS_CFLP (INSTANCE inp, int fType, IloModel & model, IloCplex & cplex)
Define the Single-source Capacitated Facility Location Model [Nominal].
References INSTANCE::c, INSTANCE::d, env, INSTANCE::f, INSTANCE::nC, INSTANCE::nF, INSTANCE::s, x_ilo, and y_ilo.
Referenced by main().
gen()
mt19937_64 gen (seed)
64-bit Mersenne Twister by Matsumoto and Nishimura, 2000
Referenced by define_budget_support().
getCplexSol()
void getCplexSol (INSTANCE inp, IloCplex cplex, SOLUTION & opt)
END main program.
Get and store cplex solution in data structure opt
References EPSI, INSTANCE::nC, INSTANCE::nF, x_ilo, SOLUTION::xSol, y_ilo, SOLUTION::ySol, SOLUTION::zStar, and SOLUTION::zStatus.
Referenced by main().
main()
int main (int argc, char * argv[])
main program
References _FILENAME, cplex(), define_MS_CFLP(), define_POLY_CFLP(), define_SOCP_CFLP(), define_SS_CFLP(), displayLimit, env, fType, getCplexSol(), model(), parseOptions(), printOptions(), printSolution(), readProblemData(), solLimit, solveCplexProblem(), support, timeLimit, and version.
model()
IloModel model (env , `cflp`)
Referenced by main().
printOptions()
void printOptions (char * _FILENAME, INSTANCE inp, int timeLimit)
Print instance info and algorithmic parameters.
References instanceType, INSTANCE::nC, INSTANCE::nF, supportType, and versionType.
Referenced by main().
printSolution()
void printSolution (char * _FILENAME, INSTANCE inp, SOLUTION opt, bool toDisk, int fullOutput)
Print solution to screen (and disk, if required)
References EPSI, instanceType, INSTANCE::nC, INSTANCE::nF, supportType, versionType, SOLUTION::xSol, SOLUTION::ySol, SOLUTION::zStar, and SOLUTION::zStatus.
Referenced by main().
read_instance_from_disk()
void read_instance_from_disk (double & epsilon, double & delta, double & gamma, int & L, int & nBl, int ** Bl, double * budget)
Read a robust instance based on budget uncertainty set.
This ensures reproducibility. We read the set $B_l$ and the budget values $b_l$. Thus, the robust instance can fully be reconstructed.
References _FILENAME.
Referenced by define_budget_support().
read_parameters_box()
void read_parameters_box (double & epsilon)
Read parameters to define the Box support.
The file 'paramsBox.txt' has the following format:
first row : epsilon, i.e., the parameter used to define the with of the box. Given a nominal demand value $d_j$, we define the interval around $d_j$ as:
 (1-\epsilon)*d_j <= d_j <= (1+\epsilon)d_j, \quad 0 \leq \epsilon \leq 1 
Referenced by define_box_support().
read_parameters_budget()
void read_parameters_budget (double & epsilon, double & delta, double & gamma, int & L)
Read parameters to define the budget support.
File : paramsBudget.txt
first row : epsilon, as above
second row: delta, i.e., how the $b_l$ value (the r.h.s. value of each budget constraint) is defined. We define $b_l$ as a percentage of the total demand of customers included in the budget constraint, i.e.:
 b_l = \delta* (\sum_{j \in B_l} d_j), \quad 0 \leq \delta \leq 1 
third row : gamma, i.e., percentage of columns included in each budget constraint:
|B_l| = \lfloor \gamma n \rfloor, \quad 0 \leq \gamma \leq 1
forth row : $L \geq 1$, i.e., number of budget constraints.
Referenced by define_budget_support().
read_parameters_ellipsoidal()
void read_parameters_ellipsoidal (double & epsilon, double & Omega)
Read parameters to define the ellipsoidal uncertainty set.
We need to define two parameters:
Omega : It determines the size of the ellipsoidal, i.e., the size of the uncertainty set.
epsilon: It defines the variance of each variable $x_{ij}$. We assume that the covariance matrix is diagonal and with constant values $\epsilon$ for each element.
Referenced by define_SOCP_CFLP().
readProblemData()
int readProblemData (char * _FILENAME, int fType, INSTANCE & inp)
Read benchmark instances.
Currently, two types of instances can be imported: type 1: OR Library type 2: Avella (Test Bed 1, Test Bed A. Test Bed B)
References INSTANCE::c, INSTANCE::d, INSTANCE::f, INSTANCE::nC, INSTANCE::nF, INSTANCE::s, INSTANCE::totD, and INSTANCE::totS.
Referenced by main().
save_instance_2_disk()
void save_instance_2_disk (double epsilon, double delta, double gamma, int L, int nBl, int ** Bl, double * budget)
Save Budget Uncertainty Set Info on disk.
We save the parameters and the data needed to recreate the budget instance. This is done to ensure reproducibility of a robust instance. If we decide to save multiple versions of robust instances starting from the same nominal instances, we will have to come up with a different name coding.
References _FILENAME.
Referenced by define_budget_support().
solveCplexProblem()
int solveCplexProblem (IloModel model, IloCplex cplex, INSTANCE inp, int solLimit, int timeLimit, int displayLimit)
Set cplex parameters and solve the optimization problem.
References env.
Referenced by main().
Variable Documentation
_FILENAME
char* _FILENAME
Instance name file.
name of the instance file
Referenced by main(), parseOptions(), read_instance_from_disk(), and save_instance_2_disk().
_MAXRANDOM
const long _MAXRANDOM = 2147483647
delta_ilo
IloNumVarArray delta_ilo
Referenced by define_POLY_CFLP().
displayLimit
int displayLimit = 4
Referenced by main().
env
IloEnv env
Referenced by define_MS_CFLP(), define_POLY_CFLP(), define_SOCP_CFLP(), define_SS_CFLP(), main(), and solveCplexProblem().
EPSI
const double EPSI = 0.00001
Referenced by getCplexSol(), and printSolution().
fType
int fType
instance type (1-4)
instance type (1-2)
Referenced by main(), and parseOptions().
INFTY
double INFTY = std::numeric_limits<double>::infinity()
inp
 INSTANCE inp
Instance data.
instanceType
string instanceType
Referenced by parseOptions(), printOptions(), and printSolution().
opt
 SOLUTION opt
Solution data structure.
psi_ilo
 TwoD psi_ilo
Referenced by define_POLY_CFLP().
q_ilo
IloNumVarArray q_ilo
Referenced by define_SOCP_CFLP().
seed
const int seed = 27
Initialization of Random Number Generator.
solLimit
int solLimit = 9999
Referenced by main().
support
int support
1-Box; 2-Budget
Referenced by main(), and parseOptions().
supportType
string supportType
Referenced by parseOptions(), printOptions(), and printSolution().
timeLimit
int timeLimit
wall-clock time limit
Referenced by main(), and parseOptions().
u_ilo
IloNumVarArray u_ilo
Referenced by define_POLY_CFLP().
version
int version
1-SS; 2-MS; 3-SOCP
1-SS; 2-MS; 3-Ellipsoidal; 4-Polyhedral
Referenced by main(), and parseOptions().
versionType
string versionType
Referenced by parseOptions(), printOptions(), and printSolution().
w_ilo
IloNumVar w_ilo
Referenced by define_SOCP_CFLP().
x_ilo
 TwoD x_ilo
Referenced by define_MS_CFLP(), define_POLY_CFLP(), define_SOCP_CFLP(), define_SS_CFLP(), and getCplexSol().
y_ilo
IloNumVarArray y_ilo
Referenced by define_MS_CFLP(), define_POLY_CFLP(), define_SOCP_CFLP(), define_SS_CFLP(), and getCplexSol().
ZERO
const double ZERO = 0.0e0